data:
  type: image
  train_dir: ../MS1M-V3
  test_dir: ../MS1M-V3
  img_size: 112
dvae:
  name: BetaVAE_H
  runname: dvae_celeba_aligned
  ckptname: last 
  c_dim: 20
  nc: 3
generator:
  name: resnet3
  kwargs:
    nfilter: 64
    nfilter_max: 512
discriminator:
  name: resnet3
  kwargs:
    nfilter: 64
    nfilter_max: 512
z_dist:
  type: gauss
  dim: 256
training:
  g_weight: 1.0
  d_weight: 1.0
  reg_param: 10.
  w_info: 0.001
  batch_size: 24
  nworkers: 4
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 10000
  inception_every: -1
  print_every: 1000
  save_every: 900
  backup_every: 50000
  max_iter: 300000
  restart_every: -1
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  nsamples_fid: 50000
  batch_size: 128
  use_model_average: true
